spring.application.name=hemobit
spring.datasource.url=jdbc:postgresql://localhost:5432/hemobit
spring.datasource.username=postgres
spring.datasource.password=hemobit123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true